shows = {'Fruits Basket (2019)': 12,
'Senryuu Shoujo': 12,
'Midara na Ao-chan wa Benkyou ga Dekinai': 12,
'Hitoribocchi no Marumaru Seikatsu': 12,
'Black Clover': 88,
'Isekai Quartet': 11,
'Sewayaki Kitsune no Senko-san': 10,
'Tate no Yuusha no Nariagari': 24,
'Kenja no Mago': 11,
'Amazing Stranger': 11,
'Joshikausei': 11,
'Nobunaga-sensei no Osanazuma': 11,
'Kimetsu no Yaiba': 11,
'Bokutachi wa Benkyou ga Dekinai': 11,
'One Punch Man S2': 10,
"JoJo's Bizarre Adventure - Golden Wind": 35}